### ISSUE TITLE
Padding added on *No Padding Option* on SpriteAtlas

### ISSUE THREAD

**Issue by UnknownRori** [BdR76/GimpSpriteAtlas#3]
![image](https://github.com/BdR76/GimpSpriteAtlas/assets/68576836/51063a86-e920-45b4-8c4b-39bcf73757f9)

So, when I set this "Pad one pixel between sprites" to "No", I expect them to not add padding between sprites, as you can see image below this, the atlas has 1 pixel padding between sprite.

![image](https://github.com/BdR76/GimpSpriteAtlas/assets/68576836/cad1f2d7-f970-4ac5-996d-9baebf131566)

**Comment by BdR76** [comment]
Thanks for spotting this. Honestly I only ever used "Yes" and may have overlooked testing the "No" option.
